_CONVERSION(`GdaError*',`Glib::RefPtr<Error>',`Glib::wrap($3)')
_CONVERSION(`const Glib::RefPtr<Error>&', `GdaError*', `Glib::unwrap($3)')
_CONVERSION(`GdaDataModel*',`Glib::RefPtr<DataModel>',`Glib::wrap($3)')
_CONVERSION(`const Glib::RefPtr<DataModel>&', `GdaDataModel*', `Glib::unwrap($3)')
_CONVERSION(`const Glib::RefPtr<ServerProvider>&', `GdaServerProvider*', `Glib::unwrap($3)')